[package]
name = "vlsm-calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
iced = { version = "0.9.0", features = ["system", "qr_code"] }
ipnetwork = "0.20.0"
